AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false